#!/usr/bin/env python3
"""
PPO training for point-to-point navigation in a MuJoCo scene generated by ZeroToWorld.

Usage:
    python scripts/train-ppo.py <path-to-mjcf> [--steps 200000] [--output policy.zip]
"""

import argparse
import json
import os

import gymnasium as gym
import mujoco
import numpy as np
from gymnasium import spaces
from stable_baselines3 import PPO
from stable_baselines3.common.callbacks import EvalCallback
from stable_baselines3.common.vec_env import DummyVecEnv


class RoomNavEnv(gym.Env):
    """
    Gymnasium environment for 2D point-to-point navigation in a ZeroToWorld scene.

    Observation (8-dim):
        [robot_x, robot_y, robot_vx, robot_vy, target_x, target_y, dx, dy]

    Action (2-dim, continuous):
        [force_x, force_y] in [-1, 1]

    Reward:
        - Dense: distance improvement * 10
        + 100.0 bonus for reaching target (within 0.15m)
        - 10.0 penalty for collision with obstacle/wall
        - 0.01 * |action|^2 energy penalty
    """

    metadata = {"render_modes": ["human", "rgb_array"]}

    def __init__(self, mjcf_path: str, max_steps: int = 500, render_mode=None):
        super().__init__()
        self.render_mode = render_mode
        self.max_steps = max_steps
        self.step_count = 0

        self.model = mujoco.MjModel.from_xml_path(mjcf_path)
        self.data = mujoco.MjData(self.model)

        # Floor bounds for random spawn/target placement
        floor_id = mujoco.mj_name2id(self.model, mujoco.mjtObj.mjOBJ_GEOM, "floor")
        self.floor_half_w = self.model.geom_size[floor_id, 0]
        self.floor_half_d = self.model.geom_size[floor_id, 1]
        self.spawn_margin = 0.3

        # Robot body id for collision detection
        self.robot_body_id = mujoco.mj_name2id(
            self.model, mujoco.mjtObj.mjOBJ_BODY, "robot"
        )

        # Action: 2D force
        self.action_space = spaces.Box(
            low=-1.0, high=1.0, shape=(2,), dtype=np.float32
        )

        # Observation: robot_pos(2) + robot_vel(2) + target_pos(2) + delta(2)
        high = np.inf * np.ones(8, dtype=np.float32)
        self.observation_space = spaces.Box(-high, high, dtype=np.float32)

        self.reach_threshold = 0.15
        self.target_pos = np.zeros(2)
        self.prev_dist = 0.0

    def _random_pos(self) -> np.ndarray:
        x = np.random.uniform(
            -self.floor_half_w + self.spawn_margin,
            self.floor_half_w - self.spawn_margin,
        )
        y = np.random.uniform(
            -self.floor_half_d + self.spawn_margin,
            self.floor_half_d - self.spawn_margin,
        )
        return np.array([x, y])

    def _get_obs(self) -> np.ndarray:
        robot_x = self.data.sensordata[0]
        robot_y = self.data.sensordata[1]
        robot_vx = self.data.sensordata[2]
        robot_vy = self.data.sensordata[3]

        dx = self.target_pos[0] - robot_x
        dy = self.target_pos[1] - robot_y

        return np.array(
            [
                robot_x,
                robot_y,
                robot_vx,
                robot_vy,
                self.target_pos[0],
                self.target_pos[1],
                dx,
                dy,
            ],
            dtype=np.float32,
        )

    def _check_collision(self) -> bool:
        for i in range(self.data.ncon):
            contact = self.data.contact[i]
            body1 = self.model.geom_bodyid[contact.geom1]
            body2 = self.model.geom_bodyid[contact.geom2]
            if body1 == self.robot_body_id or body2 == self.robot_body_id:
                other_body = body2 if body1 == self.robot_body_id else body1
                other_name = mujoco.mj_id2name(
                    self.model, mujoco.mjtObj.mjOBJ_BODY, other_body
                )
                # Ignore world body (floor contact)
                if other_name and other_name != "world":
                    return True
        return False

    def reset(self, seed=None, options=None):
        super().reset(seed=seed)
        mujoco.mj_resetData(self.model, self.data)

        # Random robot start
        start = self._random_pos()
        self.data.qpos[0] = start[0]
        self.data.qpos[1] = start[1]

        # Random target (at least 0.5m from start)
        for _ in range(100):
            self.target_pos = self._random_pos()
            if np.linalg.norm(self.target_pos - start) > 0.5:
                break

        # Move mocap body to target position
        self.data.mocap_pos[0, 0] = self.target_pos[0]
        self.data.mocap_pos[0, 1] = self.target_pos[1]
        self.data.mocap_pos[0, 2] = 0.01

        mujoco.mj_forward(self.model, self.data)

        self.step_count = 0
        self.prev_dist = np.linalg.norm(self.target_pos - start)

        return self._get_obs(), {}

    def step(self, action):
        self.data.ctrl[0] = action[0]
        self.data.ctrl[1] = action[1]

        # Multiple sub-steps for physics stability
        for _ in range(10):
            mujoco.mj_step(self.model, self.data)

        self.step_count += 1
        obs = self._get_obs()

        robot_pos = np.array([obs[0], obs[1]])
        dist = np.linalg.norm(self.target_pos - robot_pos)

        # Dense reward: improvement in distance
        reward = (self.prev_dist - dist) * 10.0
        self.prev_dist = dist

        # Energy penalty
        reward -= 0.01 * np.sum(action**2)

        # Collision penalty
        collision = self._check_collision()
        if collision:
            reward -= 10.0

        # Success bonus
        reached = dist < self.reach_threshold
        if reached:
            reward += 100.0

        terminated = reached or collision
        truncated = self.step_count >= self.max_steps

        return obs, reward, terminated, truncated, {"reached": reached, "collision": collision}


def main():
    parser = argparse.ArgumentParser(description="Train PPO navigation agent")
    parser.add_argument("mjcf_path", help="Path to the .mjcf XML file")
    parser.add_argument(
        "--steps", type=int, default=200_000, help="Total training timesteps"
    )
    parser.add_argument(
        "--output", default=None, help="Output policy path (default: <mjcf_dir>/policy.zip)"
    )
    parser.add_argument(
        "--eval-freq", type=int, default=10_000, help="Evaluation frequency"
    )
    parser.add_argument("--seed", type=int, default=42, help="Random seed")
    args = parser.parse_args()

    if not os.path.exists(args.mjcf_path):
        print(f"Error: MJCF file not found: {args.mjcf_path}")
        return

    output_path = args.output or os.path.join(
        os.path.dirname(args.mjcf_path) or ".", "policy.zip"
    )
    output_dir = os.path.dirname(output_path) or "."

    print(f"[train-ppo] Loading scene from {args.mjcf_path}")
    print(f"[train-ppo] Training for {args.steps:,} steps")

    env = DummyVecEnv([lambda: RoomNavEnv(args.mjcf_path)])
    eval_env = DummyVecEnv([lambda: RoomNavEnv(args.mjcf_path)])

    model = PPO(
        "MlpPolicy",
        env,
        learning_rate=3e-4,
        n_steps=2048,
        batch_size=64,
        n_epochs=10,
        gamma=0.99,
        gae_lambda=0.95,
        clip_range=0.2,
        ent_coef=0.01,
        verbose=1,
        seed=args.seed,
        tensorboard_log=os.path.join(output_dir, "tb_logs"),
    )

    eval_callback = EvalCallback(
        eval_env,
        best_model_save_path=output_dir,
        log_path=output_dir,
        eval_freq=args.eval_freq,
        n_eval_episodes=10,
        deterministic=True,
    )

    model.learn(total_timesteps=args.steps, callback=eval_callback)
    model.save(output_path)

    print(f"[train-ppo] Policy saved to {output_path}")

    meta = {
        "mjcf_path": os.path.abspath(args.mjcf_path),
        "total_steps": args.steps,
        "policy_path": os.path.abspath(output_path),
    }
    meta_path = output_path.replace(".zip", "_meta.json")
    with open(meta_path, "w") as f:
        json.dump(meta, f, indent=2)
    print(f"[train-ppo] Metadata saved to {meta_path}")


if __name__ == "__main__":
    main()
